### PR TITLE
Build on GHC 7.8.4

### PR DESCRIPTION
**Pull request by afcowie**
Control.Exception's `displayException` is new in GHC 7.10. Since the default implementation is `show`, replace use with that in an effort to have this work for participants who might only have 7.8.4 available.

AfC

### CODE REVIEW

**Comment by stephanh** [comment]
thank you @afcowie were you able to run the tests as well `cabal test`? When I tried to do it with GHC 7.8.4 I got this error:
```
cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.18.1.5, now Cabal-1.22.2.0). Additionally the compiler is different (was ghc-7.8, now ghc-7.10) which is probably the cause of the problem.
```

**Comment by afcowie** [comment]
@stephanh I'm still trying to reverse engineer the custom build scrip you put in place; I suspect that's why I can't get the tests to run. [and no, I wouldn't ordinarily submit a patch without passing the test suite first].

**Comment by stephanh** [comment]
I have to admit that I just took the build script from https://github.com/tonymorris/course and tried to emulate their set up for the workshop.

**Comment by afcowie** [comment]
@stephanh yes, with
```
Examples: 54  Tried: 54  Errors: 0  Failures: 42
```
the failures all being of the form:
```
### Failure in src/FS.hs:164: expression `(rFailure "notok") `rFinally` (return "justdoit") == (rFailure "notok" :: FS String)'
Exception: 'Prelude.undefined' (after 1 test):
```

AfC

**Comment by stephanh** [comment]
@afcowie how did you end up solving the cabal configure problem?

**Comment by afcowie** [comment]
`cabal build` goes to a different place than (sandboxed) install, test. So it was working all along (with 42 failures)

**Comment by stephanh** [comment]
Rebased and merged

**Pull request closed without merging**
